#!/usr/bin/env /usr/bin/python3
#
# Find and recommend unique songs you've never listened before based on your favorite songs in Spotify library.
#
# positional arguments:
#   {token,get-library,recommend,create-playlist,list-playlists,get-playlist}
#     token               Interactively generate Spotify access token to be able use with all other commands (Set this as
#                         env variable: access_token) Alternatively use --quiet flag: '$ export access_token=$(./discover-more token --quiet)'
#     get-library         Download all liked songs
#     recommend           Generate recommendations based on given songs (--input=<file> / or stdin) by excluding the given
#                         songs (--exclude=<file>). Saves recommendations to to --out=<file>
#     create-playlist     Create a new playlist with the name (--name=<name>) and uplod all songs from the given file
#                         (--input=<file> / or stdin).
#     list-playlists      List all playlists
#     get-playlist        Download a playlist by ID
#
# optional arguments:
#   -h, --help            show this help message and exit
#

import os
import sys
import requests
import json
import argparse
from datetime import datetime
import sys
import webbrowser
from http.server import BaseHTTPRequestHandler, HTTPServer
import re
import tempfile

ARG_PARAM_TOKEN = "token"
ARG_PARAM_GET_LIBRARY = "get-library"
ARG_PARAM_GET_RECOMMENDATIONS = "recommend"
ARG_PARAM_GET_PLAYLIST = "get-playlist"
ARG_PARAM_LIST_PLAYLIST = "list-playlists"
ARG_PARAM_CREATE_PLAYLIST = "create-playlist"


def delete_file(fpath):
    if os.path.exists(fpath):
        os.remove(fpath)


def eprint(*args, **kwargs):
    print(*args, file=sys.stderr, **kwargs)


def ensure_exist(fpath):
    if os.path.exists(fpath) == False:
        eprint(f"File does not exist: {fpath}")
        exit(3)


def get_access_token():
    token = os.getenv("access_token")
    if token == None or token == "":
        eprint("Must set access_token env variable")
        exit(1)
    return token


def from_stdio_if_no_atty(file):
    if sys.stdin.isatty():
        return file

    temp = tempfile.NamedTemporaryFile(delete=False)
    for line in sys.stdin.readlines():
        temp.write(str.encode(line))

    print(
        f"WARNING: Reading from stdin (using temp file {temp.name}) instead of {file}"
    )
    return temp.name


def delete_if_no_atty(file):
    if not sys.stdin.isatty():
        delete_file(file)


def spotify_api_call(path, params=None):
    access_token = get_access_token()

    path = f"https://api.spotify.com/{path}"
    rsp = None

    if params == None:
        # get
        rsp = requests.get(
            path,
            headers={"Authorization": f"Bearer {access_token}"},
        )
    else:
        # post
        rsp = requests.post(
            path, json=params, headers={"Authorization": f"Bearer {access_token}"}
        )

    if rsp.status_code >= 300:
        eprint(
            f"Invalid status code from spotify [{path}]: {rsp.status_code}\n{rsp.text}"
        )

        if rsp.status_code == 403:
            print("Try this to get access token")
            print("1. Goto: https://developer.spotify.com/console/post-playlists/")
            print("2. Click: GET TOKEN")
            print(
                "3. Tick both scopes at the top (playlist-modify-public, playlist-modify-private)"
            )
            print(
                "4. Click 'Request Token', and copy the OAuth Token and run the command"
            )
            print('   export access_token="{ACCESS_TOKEN}"')
        return None, None

    return (json.loads(rsp.text), rsp.text)


def init_args():
    FILE_NAME_LIBRARY = "spo_library.tsv"
    FILE_NAME_RECOMMENDATAION = "spo_recommendations.tsv"

    parser = argparse.ArgumentParser(
        description="Find and recommend unique songs you've never listened before based on your favorite songs in Spotify library."
    )
    cmd = parser.add_subparsers(dest="command")

    # get access token
    token = cmd.add_parser(
        ARG_PARAM_TOKEN,
        help="Interactively generate Spotify access token to be able use with all other commands (Set this as env variable: access_token)\nAlternatively use --quiet flag: '$ export access_token=$(./discover-more token --quiet)'",
    )
    token.add_argument(
        "--quiet",
        help="Quiet mode (outputs the access_token to stdio)",
        action="store_true",
    )

    # download playlist/library
    library = cmd.add_parser(ARG_PARAM_GET_LIBRARY, help="Download all liked songs")
    library.add_argument(
        "--out",
        help=f"Outfile file path [optional, default {FILE_NAME_LIBRARY}]",
        default=FILE_NAME_LIBRARY,
    )

    # recommend songs based on seed (--input, a tsv file)
    recommend = cmd.add_parser(
        ARG_PARAM_GET_RECOMMENDATIONS,
        help="Generate recommendations based on given songs (--input=<file> / or stdin) by excluding the given songs (--exclude=<file>). Saves recommendations to to --out=<file>",
    )
    recommend.add_argument(
        "--input",
        help=f"Generate recommendations based on tracks in file path [optional, default {FILE_NAME_LIBRARY}]",
        default=FILE_NAME_LIBRARY,
    )
    recommend.add_argument(
        "--out",
        help=f"Outfile file path [optional, default {FILE_NAME_RECOMMENDATAION}]",
        default=FILE_NAME_RECOMMENDATAION,
    )
    recommend.add_argument(
        "--exclude",
        help=f"Comma separated files with tracks to exclude in this mix [optional]",
    )

    # create playlist from recommendations (--input, a tsv file, --name, name)
    cplaylist = cmd.add_parser(
        ARG_PARAM_CREATE_PLAYLIST,
        help="Create a new playlist with the name (--name=<name>) and uplod all songs from the given file (--input=<file> / or stdin).",
    )
    cplaylist.add_argument(
        "--input",
        help=f"The file containing all songs details (default: {FILE_NAME_RECOMMENDATAION})",
        default=FILE_NAME_RECOMMENDATAION,
    )
    cplaylist.add_argument("--name", help=f"Name of the playlist", required=True)

    # basic command to talk to spotify
    # list playlists in stdout
    getallplaylists = cmd.add_parser(ARG_PARAM_LIST_PLAYLIST, help="List all playlists")
    # download playlists
    downloadplaylist = cmd.add_parser(
        ARG_PARAM_GET_PLAYLIST, help="Download a playlist by ID"
    )
    downloadplaylist.add_argument(
        "--id", help=f"id of the playlist to dowload", required=True
    )
    downloadplaylist.add_argument(
        "--out",
        help=f"Output file to write (use stdout if not specified)",
    )

    return parser


# ------------------------------------------------------------


def handle_load_recommendataion(infile, outfile, exclude=None):
    def load_file(fpath, dest_hashmap, dest_ids=None):
        f = open(fpath, "r")

        titles = []
        ids = []
        for line in f.readlines():
            if line.startswith("#"):
                continue

            parts = line.split("\t")
            if len(parts) < 2:
                continue
            id = parts[0]
            title = parts[1].strip()
            titles.append(title)
            ids.append(id)

        f.close()

        print(f"Loading {len(ids)} tracks from {fpath}...")
        for i in range(0, len(ids)):
            id = ids[i]
            title = titles[i]

            dest_hashmap[id] = title
            dest_hashmap[title] = id  # make sure song with same title is excluded
            if dest_ids != None:
                dest_ids.append(id)

    print(f"Generating recommendations from {infile} to {outfile}")
    # load library
    if os.path.exists(infile) == False:
        handle_load_library(infile)

    # load library into memory
    exclude_tracks_hm = (
        {}
    )  # hashmap for quick lookup if a track is already loaded, library is already included
    seed_ids = []  # the ids used as seed for recommendataion
    counts = {}  # id, count
    all_tracks = {}  # id, data
    # load seeds
    load_file(infile, exclude_tracks_hm, seed_ids)
    exclude_ids = seed_ids

    # load exclude lists (if any)
    if exclude != None:
        paths = exclude.split(",")
        for path in paths:
            load_file(path, exclude_tracks_hm, None)  # None - to not used them as seed

    print(
        f"Generating recommendation based on {len(seed_ids)}s and {len(exclude_tracks_hm)} excluded tracks..."
    )
    # download recommendataion
    delete_file(outfile)
    rec_file = open(outfile, "a")
    # header
    rec_file.write("# id\ttitle\tartist_name\talbum_name\tpopularity\n")
    i = 0
    while i < len(seed_ids):
        print(f"Loading recommmendations {i}/{len(seed_ids)}...", end="")

        ids = ",".join(map(lambda x: (x), seed_ids[i : i + 5]))

        # get recommendation
        (resp, raw) = spotify_api_call(
            f"v1/recommendations?limit=100&seed_tracks={ids}"
        )
        if resp == None:
            continue

        tracks = resp["tracks"]
        num_added = 0
        num_skipped = 0
        for item in tracks:
            id = item["id"]
            title = item["name"]
            album_name = item["album"]["name"]
            artist_name = item["artists"][0]["name"]
            popularity = item["popularity"]

            counts[id] = counts.get(id, 0) + 1
            all_tracks[id] = (title, album_name, artist_name, popularity)

            if (
                exclude_tracks_hm.__contains__(id) == False
                and exclude_tracks_hm.__contains__(title) == False
            ):
                num_added += 1
                rec_file.write(
                    f"{id}\t{title}\t{artist_name}\t{album_name}\t{popularity}\n"
                )
                exclude_tracks_hm[id] = title
            else:
                num_skipped += 1

        print(f": {num_added} added, {num_skipped} skipped.")

        i += 5

    rec_file.close()
    print("Sorting")

    os.system(
        f"cat {outfile} | (sed -u 1q; sort -nrk 5 -t '\t') > {outfile}_sorted.tsv"
    )
    os.system(f"mv {outfile}_sorted.tsv {outfile}")

    print(f"{outfile}: Recommendations ordered by spotify popularity.")

    # save most recommended tracks to a separate file
    sorted_counts = sorted(counts.items(), key=lambda x: x[1], reverse=True)

    outfile = outfile[:-4] + "_top.tsv"
    delete_file(outfile)
    rec_file = open(outfile, "a")
    # header
    rec_file.write("# id\ttitle\tartist_name\talbum_name\tpopularity\n")

    for item in sorted_counts:
        id = item[0]
        item = all_tracks[id]
        (title, album_name, artist_name, popularity) = item
        rec_file.write(f"{id}\t{title}\t{artist_name}\t{album_name}\t{popularity}\n")
    rec_file.close()

    print(f"{outfile}: Recommendations ordered by your unique taste.")


def handle_load_library(ofile):

    delete_file(ofile)

    library_file = open(ofile, "a")
    # header
    library_file.write("# id\ttitle\tartist_name\talbum_name\n")
    offset = 0
    print("Downloading library...")

    while True:
        print(f"Downloading library (offset: {offset})")
        (resp, raw) = spotify_api_call(f"v1/me/tracks?limit=50&offset={offset}")
        if resp == None:
            break

        tracks = resp["items"]

        if len(tracks) == 0:
            break

        for item in tracks:
            track = item["track"]
            id = track["id"]
            title = track["name"]
            album_name = track["album"]["name"]
            artist_name = track["artists"][0]["name"]

            library_file.write(f"{id}\t{title}\t{artist_name}\t{album_name}\n")

        offset += 50

    library_file.close()


def handle_create_playlist(infpath, playlistname):

    # read input
    infile = open(infpath, "r")
    trackIds = []
    for line in infile.readlines():
        if line.startswith("#"):
            continue

        parts = line.split("\t")
        id = f"spotify:track:{parts[0]}"
        trackIds.append(id)
    infile.close()
    total_tracks = len(trackIds)
    confirm = input(
        f'Confirm you want to add {total_tracks} songs to a new playlist "{playlistname}" (y/n): '
    )

    if confirm != "y":
        print(f'You pressed "{confirm}", Aborting')
        exit(1)

    # get user id
    (resp, raw) = spotify_api_call("v1/me")
    if resp == None:
        return
    user_id = resp["id"]

    # create playlist
    dt_string = datetime.now().strftime("%d/%m/%Y %H:%M:%S")
    dt_string_short = datetime.now().strftime("%y%m%d%H%M")
    playlistname = f"{playlistname} by discover-more @ {dt_string_short}"
    print(f"Creating playlist {playlistname}")
    (resp, raw) = spotify_api_call(
        f"v1/users/{user_id}/playlists",
        {
            "name": playlistname,
            "public": False,
            "description": f"Created by discover-more on {dt_string}",
        },
    )
    if resp == None:
        return

    playlist_id = resp["id"]

    # add tracks
    for i in range(0, len(trackIds), 100):
        print(f"Adding tracks {i}/{len(trackIds)}")
        (resp, raw) = spotify_api_call(
            f"v1/playlists/{playlist_id}/tracks", {"uris": trackIds[i : i + 100]}
        )
        if resp == None:
            return
        i += 100

    print(f"Done")


def handle_list_playlist():
    offset = 0
    while True:
        (resp, raw) = spotify_api_call(f"v1/me/playlists?limit=50&offset={offset}")
        if resp == None or len(resp["items"]) == 0:
            return

        for item in resp["items"]:
            id = item["id"]
            title = item["name"]

            print(f"{id}\t{title}")
        offset += 50


def handle_get_playlist(playlist_id):
    if playlist_id.__contains__("\t"):
        # handle when the output of list-playlists is piped
        playlist_id = playlist_id.split("\t")[0]

    (resp, _) = spotify_api_call(f"v1/playlists/{playlist_id}?fields=name")
    if resp == None:
        eprint(f"Error getting playlist with id: {playlist_id}")
        exit(5)
    title = resp["name"]
    print(f"# Playlist: {playlist_id}\t{title}")
    print("# id\ttitle\tartist_name\talbum_name\tpopularity\n")

    offset = 0
    while True:
        fields = (
            "fields=items(track(id%2Cname%2Cpopularity%2Calbum(name)%2Cartists(name)))"
        )
        (resp, _) = spotify_api_call(
            f"v1/playlists/{playlist_id}/tracks?limit=50&offset={offset}&fields={fields}"
        )
        if resp == None or len(resp["items"]) == 0:
            return

        for item in resp["items"]:
            track = item["track"]
            if track == None:
                break

            id = track["id"]
            if id == None:
                continue

            title = track["name"]
            album_name = track["album"]["name"]
            artist_name = track["artists"][0]["name"]
            popularity = track["popularity"]

            print(f"{id}\t{title}\t{artist_name}\t{album_name}\t{popularity}")
        offset += 50


def handle_token(quiet=False):
    host_name = "localhost"
    port = 5050
    client_id = "eb8d4dea271742018bc3ef2ee8290968"
    redirect_uri = f"http://{host_name}:{port}/"
    scopes = "user-library-read,playlist-modify-private,playlist-read-private"

    url = f"https://accounts.spotify.com/authorize?client_id={client_id}&redirect_uri={redirect_uri}&scope={scopes}&response_type=token"
    if quiet == False:
        print("Authorize the request and come back when you are asked.")
    webbrowser.open(url)

    class CallbackServer(BaseHTTPRequestHandler):
        def do_GET(self):
            # step 2: get access token from query string
            if self.path.__contains__("?access_token="):
                self.send_response(200)
                self.send_header("Content-type", "text/html")
                self.end_headers()
                self.wfile.write(
                    bytes("<html><head><title>Discover More</title></head>", "utf-8")
                )
                self.wfile.write(bytes('<body style="background-color:#000">', "utf-8"))
                self.wfile.write(
                    bytes(
                        '<h1 style="font-family: sans serif;padding: 20px 20px;color: aqua;">Go back to your terminal</h1>',
                        "utf-8",
                    )
                )
                self.wfile.write(
                    bytes(
                        "<script>setTimeout(function(){window.close()}, 2000);</script>",
                        "utf-8",
                    )
                )
                self.wfile.write(bytes("</body></html>", "utf-8"))

                regex = r"access_token=([^&]*)"
                match = re.finditer(regex, self.path, re.MULTILINE).__next__()
                token = match.group(1)
                cmd = f'export access_token="{token}"'
                if quiet == False:
                    print(
                        "Success! run the following command to save the access token (it's also copied into the clipboard)"
                    )
                    print("------------------------------------------------------")
                    print(cmd)
                    print("------------------------------------------------------")

                    os.system(f"echo '{cmd}' | xclip -selection clipboard")
                else:
                    print(token)
                exit(0)

            # step 1: send a js code to redirect with the code
            self.send_response(200)
            self.send_header("Content-type", "text/html")
            self.end_headers()
            self.wfile.write(
                bytes("<html><head><title>Callback</title></head>", "utf-8")
            )
            self.wfile.write(bytes('<body style="background-color:#000">', "utf-8"))
            self.wfile.write(
                bytes(
                    "<script>location.href = `/?${location.hash.substr(1)}`;</script>",
                    "utf-8",
                )
            )
            self.wfile.write(bytes("</body></html>", "utf-8"))

        def log_message(self, format, *args):
            return

    webServer = HTTPServer((host_name, port), CallbackServer)
    try:
        webServer.serve_forever()
    except KeyboardInterrupt:
        pass

    webServer.server_close()
    print("Server stopped.")


def main():
    parser = init_args()

    args = parser.parse_args()

    if args.command == None:
        parser.print_help()
        exit(3)

    if args.command == ARG_PARAM_TOKEN:
        handle_token(args.quiet)

    _ = get_access_token()  # validate access token

    if args.command == ARG_PARAM_GET_LIBRARY:
        handle_load_library(args.out)
    elif args.command == ARG_PARAM_GET_RECOMMENDATIONS:
        # prefer piped input over passed file
        args.input = from_stdio_if_no_atty(args.input)
        handle_load_recommendataion(args.input, args.out, args.exclude)
        delete_if_no_atty(args.input)
    elif args.command == ARG_PARAM_CREATE_PLAYLIST:
        # prefer piped input over passed file
        args.input = from_stdio_if_no_atty(args.input)
        handle_create_playlist(args.input, args.name)
        delete_if_no_atty(args.input)
    elif args.command == ARG_PARAM_LIST_PLAYLIST:
        handle_list_playlist()
    elif args.command == ARG_PARAM_GET_PLAYLIST:
        handle_get_playlist(args.id)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
